apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: httpbin
    env: test
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      env: test
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
      - image: kennethreitz/httpbin
        name: httpbin
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "768Mi"
          limits:
            memory: "1024Mi"
